extends: node-services

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  # Strict Mode
  strict: [1, never]

  # Stylistic Issues
  eol-last: [1, never]
  func-style: [2, expression]
  indent: [1, 2]
  quotes: [1, single, {avoidEscape: true}]
  semi: [1, never]
  require-jsdoc: [1, {require: {
    FunctionDeclaration: true,
    MethodDefinition: true,
    ClassDeclaration: true,
    ArrowFunctionExpression: true
  }}]